### PR TITLE
Add AppVeyor support.

### PR DESCRIPTION
**Pull request by XhmikosR**
@pocketjoso: this is WIP.

I need you first to add AppVeyor to the repo, then go to settings and choose skip branches without appveyor.yml. And also, paste here the AppVeyor badge URL for the master branch.

### CODE REVIEW

**Comment by pocketjoso** [comment]
Cool, thanks for the PR! Will sort this out during the weekend. Please ping me if I forget.

**Comment by pocketjoso** [comment]
Hmm Appveyor requests organisational info from my github account, which I don't want to share. I don't see any way to only allow partial access?

**Comment by XhmikosR** [comment]
I don't think there is another way currently. But it doesn't do anything fishy as far as I can tell.

```
Read org and team membership
Access user email addresses (read-only)
```

**Comment by pocketjoso** [comment]
The company I work for (Snips) has extremely strict privacy rules. The problem is not what AppVeyor does currently with the access, but what such access allows them to do... I'll look into it to see if there's a way around this.

**Comment by XhmikosR** [comment]
You do not need to grant access for the orgs. You can control each org separately IIRC.

**Comment by pocketjoso** [comment]
How?

screen shot 2016-08-27 at 09 24 06

**Comment by XhmikosR** [comment]
If you disable integration for the org you want.

`https://github.com/organizations/snipsco/settings/oauth_application_policy`

**Comment by pocketjoso** [comment]
I'll look into it - will know the answer next week.

**Comment by pocketjoso** [comment]
So I did look into this and we (Snips) can't change our organization oath policy.
I'm talking to AppVeyor but it seems like I won't be able to add this CI, for now.

**Comment by XhmikosR** [comment]
It's your project, and your decision, but to me this is insane. We are talking about a CI for a platform you didn't test, don't test and probably won't test personally.

And since other projects depends on your project, it's a shame not to make sure your projects doesn't break break.

That being said, closing this, and no worries.

**Comment by pocketjoso** [comment]
@XhmikosR I completely understand and agree with you, I just don't have a workaround for the blockers for this. If you have a solution that doesn't involve my company changing their policies (and not me creating a separate github account either please) then please let me know so we can get this merged in.

**Comment by XhmikosR** [comment]
The only solution is running this on a fork, unfortunately. I can't see any other solution.

I guess other projects like critical which have AppVeyor will inform you if this happens again.

In the meantime, might be worth cutting a new release if you think things are stable enough.

**Comment by pocketjoso** [comment]
> The only solution is running this on a fork, unfortunately.

Running what on a fork, `Penthouse`? `AppVeyor`?

As for a new release, I wasn't going to cut one because almost nothing changed, but sure I can cut a `patch` release.

**Comment by pocketjoso** [comment]
https://github.com/pocketjoso/penthouse/releases/tag/v0.9.13

**Pull request closed without merging**
