### PR TITLE
add version argument to CLI

### PR DESCRIPTION
**Pull request by pocketjoso**
Want to be able to handle `penthouse -v`, not sure this is the right way. cc @fatso83 .

### CODE REVIEW

**Comment by fatso83** [comment]
Seems fine. But wouldn't it be more appropriate to put it in the module actually handling all the other options parsing? Single Responsibility Principle, etc.

**Comment by pocketjoso** [comment]
Thought it would be awkward because still have to do the check outside, but updated now.

**Comment by fatso83** [comment]
You know, I am an idiot at times... Your first attempt was the best, since
the last commit will produce failing code AFAI can tell. The require call
(in options-parser) will work in Node-code, but will fail to resolve at
run-time for PhantomJS. If you need a way of querying the version number
for the phantomjs script (without Node), the version number will have to be
built in at build time. That seems awkward ... So I guess it's mostly just
relevant for Node, in which case your first shot was probably the best.

Sorry for the slow thinking.

**Comment by pocketjoso** [comment]
That's all right, was kind of what I intuitively thought. Will just drop the fixup and merge.

Cheers.

**Pull request merged**
