### PR TITLE
Change how inversed media queries are handled

### PR DESCRIPTION
**Pull request by raxbg**
Resolves issues with handling inversed media queries like the one in #195

### CODE REVIEW

**Comment by pocketjoso** [comment]
Hi, thanks for the PR!

Can you add a test case to verify your changes?

When I tested myself the [test case that was mentioned in the previous issue](https://github.com/pocketjoso/penthouse/issues/195#issuecomment-344868518) it still fails:
```
❌ media query should have been kept: 
    @media not all and (min-width: 50em)
```

To test this I added these two media queries mentioned in the issue into the into the test suite (https://github.com/pocketjoso/penthouse/blob/master/test/pre-formatting.test.js#L36)[here]:

Once we have a test that can demonstrate that this change works I'll merge it!

PS. when working on the test suite you have to run yarn transpile before running the test (`node_modules/.bin/jest test/pre-formatting.test.js` would be the fastest here), otherwise your changes are not taken into account. DS.

**Comment by raxbg** [comment]
Hi,

Thanks for the feedback and the guidance in adding the needed tests! I just want to make sure we are on the same page regarding the `em` based query.

It looks like the `mediaToAlwaysKeep` array is used in two viewport sizes - 1300px and 1600px. Converting the example to `px` it will look like this: 
`@media not all and (min-width: 800px)` because `1em` = `16px` (see [here](https://github.com/ericf/css-mediaquery/blob/34ba6343938e72b270205447b297611c40140a4f/index.js#L171)), in which case the media should in fact be dropped instead of kept because `all and (min-width: 800px)` is `true` so inversing it means it doesn't pass the tests.

In order to make the test correct for these viewports I have used `101em`. I believe this should be a more accurate test, please let me know if I am missing anything.

**Comment by pocketjoso** [comment]
Thanks for the update! You're right, I had missed that the tests were checking on viewport sizes 1300px and 1600px. 

This looks good now, will merge!

**Comment by pocketjoso** [comment]
Released as `penthouse@2.2.4`.

**Pull request merged**
