### PR TITLE
Added forceExclude

### PR DESCRIPTION
**Pull request by futureweb**
https://github.com/pocketjoso/penthouse/issues/243
Signed-off-by: Andreas Schnederle-Wagner <schnederle@futureweb.at>

### CODE REVIEW

**Comment by pocketjoso** [comment]
Thanks for the PR and great job with your first contribution written for Node! 👏
Just heads up - after merging I will do some minor code clean up just to avoid repetition, but don't worry about that.

**Comment by pocketjoso** [comment]
Just if you are curious:
- tidy up in this commit: https://github.com/pocketjoso/penthouse/commit/c8acaaafe89c683da943e36c031b2b3fa8958ed9
- made test pass in this commit: https://github.com/pocketjoso/penthouse/commit/2d0c3df05194786f04a8afbe6169651e3514e10c

Thanks again!

**Comment by futureweb** [comment]
makes sense to consolidate the 2 Functions ... should have thought about that forehand ... ;-)
#JuniorClassCodingKnowledge 🙈😂

**Comment by pocketjoso** [comment]
Hehe no problem!

**Pull request merged**
