### PR TITLE
Timeout

### PR DESCRIPTION
**Pull request by pocketjoso**
For #71.

Requires #81.

### CODE REVIEW

**Comment by pocketjoso** [comment]
Okay, do I really have to send exit code `0` in `process.exit` handler in order to not fail tests? Oo Doesn't seem right to me..

**Comment by fatso83** [comment]
> do I really have to send exit code 0 in process.exit handler in order to not fail tests

No, you are already in the exit signal handler, and so you should not repeat the call. That might incur weird stuff, like you experience.

**Comment by pocketjoso** [comment]
Cool, I will merge once we update the options parsing like I said; don't want to merge it before as people could potentially be relying on runs with really long execution times (that would from hereon throw errors).

**Comment by pocketjoso** [comment]
Added a commit using `phantomjs'` `resourceTimeout` flag, have done some quick tests and it also seems to help a lot for the issues with pages otherwise just timing.

Putting it in the same PR as they really solve the same problem - and both these options need to be configurable in the node module, so both need to wait for overhaul of options parsing.

**Comment by pocketjoso** [comment]
Rebased on AST `penthouse` and now used as an option - ready to go!

**Pull request merged**
