### PR TITLE
Closes #111: allow for configuring phantomjs

### LINKED ISSUE #111: Allow for passing options to PhantomJS
Hi guys,

First, thank you for the great job!

Then, it would be nice to be able to tune PhantomJS, for instance in the following cases:

- to set-up a proxy server
- to accommodate websites that reject browsers using TLSv1 as "outdated" (I had the problem).

I will submit a pull request for that, hoping you'll like it!

Regards,
Nicolas

### PR DESCRIPTION
**Pull request by ndemengel**
Allows for passing an additional set of options for phantomjs:

```js
penthouse({
    ...
    phantomJsOptions: { // see `phantomjs --help` for the list of all available options
        'proxy': 'http://proxy.company.com:8080',
        'ssl-protocol': 'SSLv3'
    }
}, ...)
```

### CODE REVIEW

**Comment by pocketjoso** [comment]
Looks good, thanks! Will try to deploy new version tonight.

**Comment by pocketjoso** [comment]
Deployed as `0.9.3`. Thanks again!

**Comment by ndemengel** [comment]
Thanks to you!

**Comment by ndemengel** [comment]
Hi pocketjoso,

If I'm not mistaken, you forgot to publish version 0.9.3 to npm registry :-)

**Comment by pocketjoso** [comment]
Oops - done now!

**Comment by ndemengel** [comment]
Many thanks!

**Pull request merged**
