### PR TITLE
dev: next without multi url

### PR DESCRIPTION
**Pull request by pocketjoso**
Preparing the `dev` branch to be merged with `master`. As proposed in #41, the multi url handling previously added to `Penthouse` has now been removed. All other improvements on the `dev` branch will stay.

Tests have been updated.

### CODE REVIEW

**Comment by pocketjoso** [comment]
@fatso83 If you have time, would be good if you could give this PR a quick glance before it goes into `dev` and then into `master`. I just added new commits to remove everything I could find that relates to the multi url handling, but it's possible that I missed things that are now redundant. Like I said, I do want to continue on this branch, as many other improvements have been made (by the both of us), other than the multi url handling.

If you don't have time, don't worry, but I plan to merge by tomorrow evening.

**Comment by fatso83** [comment]
Cool. Give me a couple of hours.
7. feb. 2015 15:24 skrev "Jonas Ohlsson" <notifications@github.com>
følgende:

**Comment by pocketjoso** [comment]
@fatso83 Only the first 4 commits are related to the multi url handling. The others are to bring the `dev` branch up to par with `master` (should really be in a different PR).

**Comment by fatso83** [comment]
Have looked through all the code, but haven't run the code, so I am just assuming all tests still run. This looks good, so I would have no reservations in merging this.

**Comment by pocketjoso** [comment]
All tests do run, as can be seen by the Travis CI report.

Awesome, I intend to merge into master later today then.

**Pull request merged**
