### PR TITLE
Remove unused devDependencies and normalize package.json

### PR DESCRIPTION
**Pull request by XhmikosR**
@pocketjoso: there seems to be more dev deps unused like express, morgan and portfinder. Should I remove those too?

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hmm, tests fails which is something I couldn't test since on Windows 10/12 tests are broken. I'll see if I can figure out the issue.

**Comment by pocketjoso** [comment]
Still failing - let me have a look why.

**Comment by XhmikosR** [comment]
Yeah, don't merge this yet, I'm still experimenting with it.

**Comment by pocketjoso** [comment]
Ok, I'll wait then.

**Comment by XhmikosR** [comment]
@pocketjoso: I can't figure it out. And since I can't test locally, it's harder for me to debug this.

So I reverted the deps update, just kept the other changes.

**Comment by pocketjoso** [comment]
Okay, let's start with this and we can update deps later. 👍

**Pull request merged**
