### PR TITLE
Optional unblock js requests

### PR DESCRIPTION
**Pull request by gavro**
Add blockJSRequests option (default = true).

Makes it possible to load JS files. See discussion here: https://github.com/pocketjoso/penthouse/issues/113
Made it optional. Choice = good, even if it might be wasteful :)

### CODE REVIEW

**Comment by pocketjoso** [comment]
Sure, code looks good.

Just update the README to list the option you added, and then I'll merge. 👍

**Comment by gavro** [comment]
Awesome, thnx. Added to README. Do you need a squashed commit or are these commits fine?

**Comment by pocketjoso** [comment]
We could squash the lint error commit into the one it fixed - but not super important, will merge now as is.

Thanks for the PR!

**Comment by pocketjoso** [comment]
Published as `0.9.16`.

**Pull request merged**
